[package]
name = "nest-cli"
version = "0.1.0"
authors = ["Benjamin Grange <benjamin.grange@epitech.eu>"]
edition = "2018"

[dependencies]
libnest = { path = "../libnest" }
failure = "0.1.1"
clap = "2.32.0"
