[package]
name = "libnest"
version = "0.1.0"
authors = ["Benjamin Grange <benjamin.grange@epitech.eu>"]
description = "Nest's backend library to write a package manager for Raven."

[dependencies]
curl = "0.4.11"
serde = "1.0.33"
serde_json = "1.0.11"
serde_derive = "1.0.33"
