[package]
name = "libnest"
version = "0.1.0"
authors = ["Benjamin Grange <benjamin.grange@epitech.eu>"]
edition = "2018"

[dependencies]
error-chain = "0.12.0"
failure = "0.1.3"
lazy_static = "1.2.0"
semver = "0.9.0"
serde = "1.0.82"
serde_derive = "1.0.82"
toml = "0.4.10"
url_serde = "0.2.0"
